apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
      version: blue
  template:
    metadata:
      labels:
        app: bankapp
        version: blue
    spec:
      containers:
      - name: bankapp
        image: rhaloubi8/bankapp:${TAG}  # <-- Use the pipeline tag here
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
